# Generated by Django 5.2.3 on 2025-10-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
